CREATE DATABASE teaspoon;

USE teaspoon;

CREATE TABLE sample(
	NO INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100)
);

INSERT INTO sample VALUES(DEFAULT, '홍길동');
INSERT INTO sample VALUES(DEFAULT, '강감찬');
INSERT INTO sample VALUES(DEFAULT, '이순신');
INSERT INTO sample VALUES(DEFAULT, '서광');
INSERT INTO sample VALUES(DEFAULT, '이소윤');

CREATE TABLE board(
	seq INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	nickname VARCHAR(20),
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP(),
	visited INT DEFAULT 0
	); 
	
INSERT INTO board VALUES(DEFAULT, '제목1', '내용1', 'author1', DEFAULT, DEFAULT); 
INSERT INTO board VALUES(DEFAULT, '제목2', '내용2', 'author2', DEFAULT, DEFAULT); 
INSERT INTO board VALUES(DEFAULT, '제목3', '내용3', 'author3', DEFAULT, DEFAULT); 
INSERT INTO board VALUES(DEFAULT, '제목4', '내용4', 'author4', DEFAULT, DEFAULT); 
INSERT INTO board VALUES(DEFAULT, '제목5', '내용5', 'author5', DEFAULT, DEFAULT); 